// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MonitLog.proto

package com.vanilla.protocol.protobuf;

public final class MonitLogProto {
  private MonitLogProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MonitLogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string msgId = 1;
    /**
     * <code>required string msgId = 1;</code>
     */
    boolean hasMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    java.lang.String getMsgId();
    /**
     * <code>required string msgId = 1;</code>
     */
    com.google.protobuf.ByteString
        getMsgIdBytes();

    // required string level = 2;
    /**
     * <code>required string level = 2;</code>
     */
    boolean hasLevel();
    /**
     * <code>required string level = 2;</code>
     */
    java.lang.String getLevel();
    /**
     * <code>required string level = 2;</code>
     */
    com.google.protobuf.ByteString
        getLevelBytes();

    // required string loggerName = 3;
    /**
     * <code>required string loggerName = 3;</code>
     */
    boolean hasLoggerName();
    /**
     * <code>required string loggerName = 3;</code>
     */
    java.lang.String getLoggerName();
    /**
     * <code>required string loggerName = 3;</code>
     */
    com.google.protobuf.ByteString
        getLoggerNameBytes();

    // required string localAddress = 4;
    /**
     * <code>required string localAddress = 4;</code>
     */
    boolean hasLocalAddress();
    /**
     * <code>required string localAddress = 4;</code>
     */
    java.lang.String getLocalAddress();
    /**
     * <code>required string localAddress = 4;</code>
     */
    com.google.protobuf.ByteString
        getLocalAddressBytes();

    // required sint64 timestamp = 5;
    /**
     * <code>required sint64 timestamp = 5;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required sint64 timestamp = 5;</code>
     */
    long getTimestamp();

    // optional string threadName = 6;
    /**
     * <code>optional string threadName = 6;</code>
     */
    boolean hasThreadName();
    /**
     * <code>optional string threadName = 6;</code>
     */
    java.lang.String getThreadName();
    /**
     * <code>optional string threadName = 6;</code>
     */
    com.google.protobuf.ByteString
        getThreadNameBytes();

    // optional string msg = 7;
    /**
     * <code>optional string msg = 7;</code>
     */
    boolean hasMsg();
    /**
     * <code>optional string msg = 7;</code>
     */
    java.lang.String getMsg();
    /**
     * <code>optional string msg = 7;</code>
     */
    com.google.protobuf.ByteString
        getMsgBytes();
  }
  /**
   * Protobuf type {@code push.MonitLog}
   */
  public static final class MonitLog extends
      com.google.protobuf.GeneratedMessage
      implements MonitLogOrBuilder {
    // Use MonitLog.newBuilder() to construct.
    private MonitLog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MonitLog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MonitLog defaultInstance;
    public static MonitLog getDefaultInstance() {
      return defaultInstance;
    }

    public MonitLog getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MonitLog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              msgId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              level_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              loggerName_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              localAddress_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timestamp_ = input.readSInt64();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              threadName_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vanilla.protocol.protobuf.MonitLogProto.internal_static_push_MonitLog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vanilla.protocol.protobuf.MonitLogProto.internal_static_push_MonitLog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.class, com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder.class);
    }

    public static com.google.protobuf.Parser<MonitLog> PARSER =
        new com.google.protobuf.AbstractParser<MonitLog>() {
      public MonitLog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MonitLog(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MonitLog> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string msgId = 1;
    public static final int MSGID_FIELD_NUMBER = 1;
    private java.lang.Object msgId_;
    /**
     * <code>required string msgId = 1;</code>
     */
    public boolean hasMsgId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public java.lang.String getMsgId() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string msgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMsgIdBytes() {
      java.lang.Object ref = msgId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string level = 2;
    public static final int LEVEL_FIELD_NUMBER = 2;
    private java.lang.Object level_;
    /**
     * <code>required string level = 2;</code>
     */
    public boolean hasLevel() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string level = 2;</code>
     */
    public java.lang.String getLevel() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          level_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string level = 2;</code>
     */
    public com.google.protobuf.ByteString
        getLevelBytes() {
      java.lang.Object ref = level_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        level_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string loggerName = 3;
    public static final int LOGGERNAME_FIELD_NUMBER = 3;
    private java.lang.Object loggerName_;
    /**
     * <code>required string loggerName = 3;</code>
     */
    public boolean hasLoggerName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string loggerName = 3;</code>
     */
    public java.lang.String getLoggerName() {
      java.lang.Object ref = loggerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          loggerName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string loggerName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLoggerNameBytes() {
      java.lang.Object ref = loggerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loggerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string localAddress = 4;
    public static final int LOCALADDRESS_FIELD_NUMBER = 4;
    private java.lang.Object localAddress_;
    /**
     * <code>required string localAddress = 4;</code>
     */
    public boolean hasLocalAddress() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string localAddress = 4;</code>
     */
    public java.lang.String getLocalAddress() {
      java.lang.Object ref = localAddress_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          localAddress_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string localAddress = 4;</code>
     */
    public com.google.protobuf.ByteString
        getLocalAddressBytes() {
      java.lang.Object ref = localAddress_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        localAddress_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required sint64 timestamp = 5;
    public static final int TIMESTAMP_FIELD_NUMBER = 5;
    private long timestamp_;
    /**
     * <code>required sint64 timestamp = 5;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required sint64 timestamp = 5;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    // optional string threadName = 6;
    public static final int THREADNAME_FIELD_NUMBER = 6;
    private java.lang.Object threadName_;
    /**
     * <code>optional string threadName = 6;</code>
     */
    public boolean hasThreadName() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string threadName = 6;</code>
     */
    public java.lang.String getThreadName() {
      java.lang.Object ref = threadName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          threadName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string threadName = 6;</code>
     */
    public com.google.protobuf.ByteString
        getThreadNameBytes() {
      java.lang.Object ref = threadName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        threadName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string msg = 7;
    public static final int MSG_FIELD_NUMBER = 7;
    private java.lang.Object msg_;
    /**
     * <code>optional string msg = 7;</code>
     */
    public boolean hasMsg() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string msg = 7;</code>
     */
    public java.lang.String getMsg() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string msg = 7;</code>
     */
    public com.google.protobuf.ByteString
        getMsgBytes() {
      java.lang.Object ref = msg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      msgId_ = "";
      level_ = "";
      loggerName_ = "";
      localAddress_ = "";
      timestamp_ = 0L;
      threadName_ = "";
      msg_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasMsgId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLevel()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLoggerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLocalAddress()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getLevelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getLoggerNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getLocalAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeSInt64(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getThreadNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getMsgBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getMsgIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getLevelBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getLoggerNameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getLocalAddressBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeSInt64Size(5, timestamp_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getThreadNameBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getMsgBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vanilla.protocol.protobuf.MonitLogProto.MonitLog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code push.MonitLog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vanilla.protocol.protobuf.MonitLogProto.internal_static_push_MonitLog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vanilla.protocol.protobuf.MonitLogProto.internal_static_push_MonitLog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.class, com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder.class);
      }

      // Construct using com.vanilla.msg.proto.MonitLogProto.MonitLog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        msgId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        level_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        loggerName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        localAddress_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        threadName_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        msg_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vanilla.protocol.protobuf.MonitLogProto.internal_static_push_MonitLog_descriptor;
      }

      public com.vanilla.protocol.protobuf.MonitLogProto.MonitLog getDefaultInstanceForType() {
        return com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance();
      }

      public com.vanilla.protocol.protobuf.MonitLogProto.MonitLog build() {
        com.vanilla.protocol.protobuf.MonitLogProto.MonitLog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vanilla.protocol.protobuf.MonitLogProto.MonitLog buildPartial() {
        com.vanilla.protocol.protobuf.MonitLogProto.MonitLog result = new com.vanilla.protocol.protobuf.MonitLogProto.MonitLog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.msgId_ = msgId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.level_ = level_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.loggerName_ = loggerName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.localAddress_ = localAddress_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.threadName_ = threadName_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.msg_ = msg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vanilla.protocol.protobuf.MonitLogProto.MonitLog) {
          return mergeFrom((com.vanilla.protocol.protobuf.MonitLogProto.MonitLog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vanilla.protocol.protobuf.MonitLogProto.MonitLog other) {
        if (other == com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance()) return this;
        if (other.hasMsgId()) {
          bitField0_ |= 0x00000001;
          msgId_ = other.msgId_;
          onChanged();
        }
        if (other.hasLevel()) {
          bitField0_ |= 0x00000002;
          level_ = other.level_;
          onChanged();
        }
        if (other.hasLoggerName()) {
          bitField0_ |= 0x00000004;
          loggerName_ = other.loggerName_;
          onChanged();
        }
        if (other.hasLocalAddress()) {
          bitField0_ |= 0x00000008;
          localAddress_ = other.localAddress_;
          onChanged();
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasThreadName()) {
          bitField0_ |= 0x00000020;
          threadName_ = other.threadName_;
          onChanged();
        }
        if (other.hasMsg()) {
          bitField0_ |= 0x00000040;
          msg_ = other.msg_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasMsgId()) {
          
          return false;
        }
        if (!hasLevel()) {
          
          return false;
        }
        if (!hasLoggerName()) {
          
          return false;
        }
        if (!hasLocalAddress()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vanilla.protocol.protobuf.MonitLogProto.MonitLog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vanilla.protocol.protobuf.MonitLogProto.MonitLog) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string msgId = 1;
      private java.lang.Object msgId_ = "";
      /**
       * <code>required string msgId = 1;</code>
       */
      public boolean hasMsgId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public java.lang.String getMsgId() {
        java.lang.Object ref = msgId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msgId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMsgIdBytes() {
        java.lang.Object ref = msgId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msgId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder clearMsgId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        msgId_ = getDefaultInstance().getMsgId();
        onChanged();
        return this;
      }
      /**
       * <code>required string msgId = 1;</code>
       */
      public Builder setMsgIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        msgId_ = value;
        onChanged();
        return this;
      }

      // required string level = 2;
      private java.lang.Object level_ = "";
      /**
       * <code>required string level = 2;</code>
       */
      public boolean hasLevel() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string level = 2;</code>
       */
      public java.lang.String getLevel() {
        java.lang.Object ref = level_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          level_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string level = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLevelBytes() {
        java.lang.Object ref = level_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          level_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string level = 2;</code>
       */
      public Builder setLevel(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string level = 2;</code>
       */
      public Builder clearLevel() {
        bitField0_ = (bitField0_ & ~0x00000002);
        level_ = getDefaultInstance().getLevel();
        onChanged();
        return this;
      }
      /**
       * <code>required string level = 2;</code>
       */
      public Builder setLevelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        level_ = value;
        onChanged();
        return this;
      }

      // required string loggerName = 3;
      private java.lang.Object loggerName_ = "";
      /**
       * <code>required string loggerName = 3;</code>
       */
      public boolean hasLoggerName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string loggerName = 3;</code>
       */
      public java.lang.String getLoggerName() {
        java.lang.Object ref = loggerName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          loggerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string loggerName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getLoggerNameBytes() {
        java.lang.Object ref = loggerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          loggerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string loggerName = 3;</code>
       */
      public Builder setLoggerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loggerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string loggerName = 3;</code>
       */
      public Builder clearLoggerName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        loggerName_ = getDefaultInstance().getLoggerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string loggerName = 3;</code>
       */
      public Builder setLoggerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        loggerName_ = value;
        onChanged();
        return this;
      }

      // required string localAddress = 4;
      private java.lang.Object localAddress_ = "";
      /**
       * <code>required string localAddress = 4;</code>
       */
      public boolean hasLocalAddress() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string localAddress = 4;</code>
       */
      public java.lang.String getLocalAddress() {
        java.lang.Object ref = localAddress_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          localAddress_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string localAddress = 4;</code>
       */
      public com.google.protobuf.ByteString
          getLocalAddressBytes() {
        java.lang.Object ref = localAddress_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          localAddress_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string localAddress = 4;</code>
       */
      public Builder setLocalAddress(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        localAddress_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string localAddress = 4;</code>
       */
      public Builder clearLocalAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        localAddress_ = getDefaultInstance().getLocalAddress();
        onChanged();
        return this;
      }
      /**
       * <code>required string localAddress = 4;</code>
       */
      public Builder setLocalAddressBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        localAddress_ = value;
        onChanged();
        return this;
      }

      // required sint64 timestamp = 5;
      private long timestamp_ ;
      /**
       * <code>required sint64 timestamp = 5;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required sint64 timestamp = 5;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required sint64 timestamp = 5;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000010;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required sint64 timestamp = 5;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // optional string threadName = 6;
      private java.lang.Object threadName_ = "";
      /**
       * <code>optional string threadName = 6;</code>
       */
      public boolean hasThreadName() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string threadName = 6;</code>
       */
      public java.lang.String getThreadName() {
        java.lang.Object ref = threadName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          threadName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string threadName = 6;</code>
       */
      public com.google.protobuf.ByteString
          getThreadNameBytes() {
        java.lang.Object ref = threadName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          threadName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string threadName = 6;</code>
       */
      public Builder setThreadName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        threadName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string threadName = 6;</code>
       */
      public Builder clearThreadName() {
        bitField0_ = (bitField0_ & ~0x00000020);
        threadName_ = getDefaultInstance().getThreadName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string threadName = 6;</code>
       */
      public Builder setThreadNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        threadName_ = value;
        onChanged();
        return this;
      }

      // optional string msg = 7;
      private java.lang.Object msg_ = "";
      /**
       * <code>optional string msg = 7;</code>
       */
      public boolean hasMsg() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public java.lang.String getMsg() {
        java.lang.Object ref = msg_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          msg_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public com.google.protobuf.ByteString
          getMsgBytes() {
        java.lang.Object ref = msg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          msg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder setMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder clearMsg() {
        bitField0_ = (bitField0_ & ~0x00000040);
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string msg = 7;</code>
       */
      public Builder setMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        msg_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:push.MonitLog)
    }

    static {
      defaultInstance = new MonitLog(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:push.MonitLog)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_push_MonitLog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_push_MonitLog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MonitLog.proto\022\004push\"\206\001\n\010MonitLog\022\r\n\005m" +
      "sgId\030\001 \002(\t\022\r\n\005level\030\002 \002(\t\022\022\n\nloggerName\030" +
      "\003 \002(\t\022\024\n\014localAddress\030\004 \002(\t\022\021\n\ttimestamp" +
      "\030\005 \002(\022\022\022\n\nthreadName\030\006 \001(\t\022\013\n\003msg\030\007 \001(\tB" +
      "#\n\022com.vanilla.msg.protoB\rMonitLogProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_push_MonitLog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_push_MonitLog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_push_MonitLog_descriptor,
              new java.lang.String[] { "MsgId", "Level", "LoggerName", "LocalAddress", "Timestamp", "ThreadName", "Msg", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
