// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PushMessage.proto

package com.vanilla.protocol.protobuf;

public final class PushMessageProto {
  private PushMessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PushMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 type = 1;
    /**
     * <code>required int32 type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required int32 type = 1;</code>
     */
    int getType();

    // optional string body = 2;
    /**
     * <code>optional string body = 2;</code>
     */
    boolean hasBody();
    /**
     * <code>optional string body = 2;</code>
     */
    java.lang.String getBody();
    /**
     * <code>optional string body = 2;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    // optional .push.MonitLog log = 3;
    /**
     * <code>optional .push.MonitLog log = 3;</code>
     */
    boolean hasLog();
    /**
     * <code>optional .push.MonitLog log = 3;</code>
     */
    com.vanilla.protocol.protobuf.MonitLogProto.MonitLog getLog();
    /**
     * <code>optional .push.MonitLog log = 3;</code>
     */
    com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder getLogOrBuilder();
  }
  /**
   * Protobuf type {@code push.PushMessage}
   */
  public static final class PushMessage extends
      com.google.protobuf.GeneratedMessage
      implements PushMessageOrBuilder {
    // Use PushMessage.newBuilder() to construct.
    private PushMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PushMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PushMessage defaultInstance;
    public static PushMessage getDefaultInstance() {
      return defaultInstance;
    }

    public PushMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PushMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              type_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              body_ = input.readBytes();
              break;
            }
            case 26: {
              com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = log_.toBuilder();
              }
              log_ = input.readMessage(com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(log_);
                log_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.vanilla.protocol.protobuf.PushMessageProto.internal_static_push_PushMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.vanilla.protocol.protobuf.PushMessageProto.internal_static_push_PushMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.vanilla.protocol.protobuf.PushMessageProto.PushMessage.class, com.vanilla.protocol.protobuf.PushMessageProto.PushMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<PushMessage> PARSER =
        new com.google.protobuf.AbstractParser<PushMessage>() {
      public PushMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PushMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PushMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>required int32 type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 type = 1;</code>
     */
    public int getType() {
      return type_;
    }

    // optional string body = 2;
    public static final int BODY_FIELD_NUMBER = 2;
    private java.lang.Object body_;
    /**
     * <code>optional string body = 2;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string body = 2;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .push.MonitLog log = 3;
    public static final int LOG_FIELD_NUMBER = 3;
    private com.vanilla.protocol.protobuf.MonitLogProto.MonitLog log_;
    /**
     * <code>optional .push.MonitLog log = 3;</code>
     */
    public boolean hasLog() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .push.MonitLog log = 3;</code>
     */
    public com.vanilla.protocol.protobuf.MonitLogProto.MonitLog getLog() {
      return log_;
    }
    /**
     * <code>optional .push.MonitLog log = 3;</code>
     */
    public com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder getLogOrBuilder() {
      return log_;
    }

    private void initFields() {
      type_ = 0;
      body_ = "";
      log_ = com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasLog()) {
        if (!getLog().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getBodyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, log_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getBodyBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, log_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.vanilla.protocol.protobuf.PushMessageProto.PushMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code push.PushMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.vanilla.protocol.protobuf.PushMessageProto.PushMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.vanilla.protocol.protobuf.PushMessageProto.internal_static_push_PushMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.vanilla.protocol.protobuf.PushMessageProto.internal_static_push_PushMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.vanilla.protocol.protobuf.PushMessageProto.PushMessage.class, com.vanilla.protocol.protobuf.PushMessageProto.PushMessage.Builder.class);
      }

      // Construct using com.vanilla.msg.proto.PushMessageProto.PushMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getLogFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (logBuilder_ == null) {
          log_ = com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance();
        } else {
          logBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.vanilla.protocol.protobuf.PushMessageProto.internal_static_push_PushMessage_descriptor;
      }

      public com.vanilla.protocol.protobuf.PushMessageProto.PushMessage getDefaultInstanceForType() {
        return com.vanilla.protocol.protobuf.PushMessageProto.PushMessage.getDefaultInstance();
      }

      public com.vanilla.protocol.protobuf.PushMessageProto.PushMessage build() {
        com.vanilla.protocol.protobuf.PushMessageProto.PushMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.vanilla.protocol.protobuf.PushMessageProto.PushMessage buildPartial() {
        com.vanilla.protocol.protobuf.PushMessageProto.PushMessage result = new com.vanilla.protocol.protobuf.PushMessageProto.PushMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (logBuilder_ == null) {
          result.log_ = log_;
        } else {
          result.log_ = logBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.vanilla.protocol.protobuf.PushMessageProto.PushMessage) {
          return mergeFrom((com.vanilla.protocol.protobuf.PushMessageProto.PushMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.vanilla.protocol.protobuf.PushMessageProto.PushMessage other) {
        if (other == com.vanilla.protocol.protobuf.PushMessageProto.PushMessage.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasBody()) {
          bitField0_ |= 0x00000002;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasLog()) {
          mergeLog(other.getLog());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasLog()) {
          if (!getLog().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.vanilla.protocol.protobuf.PushMessageProto.PushMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.vanilla.protocol.protobuf.PushMessageProto.PushMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 type = 1;
      private int type_ ;
      /**
       * <code>required int32 type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional string body = 2;
      private java.lang.Object body_ = "";
      /**
       * <code>optional string body = 2;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string body = 2;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          body_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string body = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 2;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 2;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 2;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        body_ = value;
        onChanged();
        return this;
      }

      // optional .push.MonitLog log = 3;
      private com.vanilla.protocol.protobuf.MonitLogProto.MonitLog log_ = com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.vanilla.protocol.protobuf.MonitLogProto.MonitLog, com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder, com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder> logBuilder_;
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public boolean hasLog() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public com.vanilla.protocol.protobuf.MonitLogProto.MonitLog getLog() {
        if (logBuilder_ == null) {
          return log_;
        } else {
          return logBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public Builder setLog(com.vanilla.protocol.protobuf.MonitLogProto.MonitLog value) {
        if (logBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          log_ = value;
          onChanged();
        } else {
          logBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public Builder setLog(
          com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder builderForValue) {
        if (logBuilder_ == null) {
          log_ = builderForValue.build();
          onChanged();
        } else {
          logBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public Builder mergeLog(com.vanilla.protocol.protobuf.MonitLogProto.MonitLog value) {
        if (logBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              log_ != com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance()) {
            log_ =
              com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.newBuilder(log_).mergeFrom(value).buildPartial();
          } else {
            log_ = value;
          }
          onChanged();
        } else {
          logBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public Builder clearLog() {
        if (logBuilder_ == null) {
          log_ = com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.getDefaultInstance();
          onChanged();
        } else {
          logBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder getLogBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLogFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      public com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder getLogOrBuilder() {
        if (logBuilder_ != null) {
          return logBuilder_.getMessageOrBuilder();
        } else {
          return log_;
        }
      }
      /**
       * <code>optional .push.MonitLog log = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.vanilla.protocol.protobuf.MonitLogProto.MonitLog, com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder, com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder> 
          getLogFieldBuilder() {
        if (logBuilder_ == null) {
          logBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.vanilla.protocol.protobuf.MonitLogProto.MonitLog, com.vanilla.protocol.protobuf.MonitLogProto.MonitLog.Builder, com.vanilla.protocol.protobuf.MonitLogProto.MonitLogOrBuilder>(
                  log_,
                  getParentForChildren(),
                  isClean());
          log_ = null;
        }
        return logBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:push.PushMessage)
    }

    static {
      defaultInstance = new PushMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:push.PushMessage)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_push_PushMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_push_PushMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021PushMessage.proto\022\004push\032\016MonitLog.prot" +
      "o\"F\n\013PushMessage\022\014\n\004type\030\001 \002(\005\022\014\n\004body\030\002" +
      " \001(\t\022\033\n\003log\030\003 \001(\0132\016.push.MonitLogB&\n\022com" +
      ".vanilla.msg.protoB\020PushMessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_push_PushMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_push_PushMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_push_PushMessage_descriptor,
              new java.lang.String[] { "Type", "Body", "Log", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.vanilla.protocol.protobuf.MonitLogProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
